import {beforeEach,afterEach,expect,it,vi} from 'vitest'
import {mount,flushPromises} from '@vue/test-utils'
const mocks=vi.hoisted(()=>({call:vi.fn()}))
vi.mock('../../../web/src/api',()=>({api:{callExtension:mocks.call}}))
import ServiceSettings from './ServiceSettings.vue'
let wrapper,config
beforeEach(()=>{
 config={version:'services-v1',embedding:{enabled:false,provider:'disabled',protocol:'openai_embeddings',base_url:'',endpoint:'',model:'',account_id:'',request_timeout_secs:30,has_key:true},search:{enabled:false,provider:'disabled',protocol:'custom',base_url:'',endpoint:'',request_timeout_secs:30,max_results:5,has_key:true},web_read:{enabled:false,request_timeout_secs:30,max_bytes:262144,allowed_hosts:[],allow_private_networks:false}}
 mocks.call.mockReset().mockImplementation(async(_,action,values)=>{if(action==='services.get')return config;if(action==='services.save')return{...values,version:'services-v2',embedding:{...values.embedding,has_key:!values.embedding.clear_key},search:{...values.search,has_key:!values.search.clear_key}};throw new Error(`Unexpected ${action}`)})
})
afterEach(()=>wrapper?.unmount())
it('可选服务默认关闭，读取只显示has_key，保存不发起模型或搜索请求',async()=>{
 wrapper=mount(ServiceSettings);await flushPromises()
 expect(wrapper.get('[aria-label="向量服务密钥"]').element.value).toBe('')
 expect(wrapper.get('[aria-label="搜索服务密钥"]').element.value).toBe('')
 expect(wrapper.get('[aria-label="单次编码字节上限"]').element.value).toBe('480')
 expect(wrapper.get('[aria-label="文档编码前缀"]').element.value).toBe('')
 expect(wrapper.get('[aria-label="查询编码前缀"]').element.value).toBe('')
 await wrapper.get('[aria-label="向量服务提供方"]').setValue('cloudflare')
 expect(wrapper.get('[aria-label="Embedding 模型"]').element.value).toBe('@cf/baai/bge-m3')
 await wrapper.get('[aria-label="Cloudflare Account ID"]').setValue('fixture-account')
 await wrapper.get('[aria-label="搜索服务提供方"]').setValue('tavily')
 await wrapper.get('[aria-label="搜索服务密钥"]').setValue('synthetic-search')
 await wrapper.get('form').trigger('submit');await flushPromises()
 const saved=mocks.call.mock.calls.find(call=>call[1]==='services.save')[2]
 expect(saved.expected_version).toBe('services-v1')
 expect(saved.embedding).toMatchObject({protocol:'cloudflare',model:'@cf/baai/bge-m3',api_key:'',max_input_bytes:480,document_prefix:'',query_prefix:''})
 expect(saved.search).toMatchObject({protocol:'tavily',api_key:'synthetic-search'})
 expect(saved.web_read.allow_private_networks).toBe(false)
 expect(saved.embedding).not.toHaveProperty('has_key')
 expect(wrapper.get('[aria-label="搜索服务密钥"]').element.value).toBe('')
 expect(mocks.call.mock.calls.every(call=>['services.get','services.save'].includes(call[1]))).toBe(true)
})
it('读取和保存独立编码上限与文档查询前缀，提示向量指纹变化需重建',async()=>{
 Object.assign(config.embedding,{max_input_bytes:2048,document_prefix:'passage: ',query_prefix:'query: '})
 wrapper=mount(ServiceSettings);await flushPromises()
 expect(wrapper.get('[aria-label="单次编码字节上限"]').element.value).toBe('2048')
 expect(wrapper.get('[aria-label="文档编码前缀"]').element.value).toBe('passage: ')
 expect(wrapper.get('[aria-label="查询编码前缀"]').element.value).toBe('query: ')
 await wrapper.get('[aria-label="单次编码字节上限"]').setValue(4096)
 await wrapper.get('[aria-label="文档编码前缀"]').setValue('文档：')
 await wrapper.get('[aria-label="查询编码前缀"]').setValue('查询：')
 await wrapper.get('form').trigger('submit');await flushPromises()
 const saved=mocks.call.mock.calls.find(call=>call[1]==='services.save')[2]
 expect(saved.embedding).toMatchObject({max_input_bytes:4096,document_prefix:'文档：',query_prefix:'查询：',enabled:false})
 expect(wrapper.text()).toContain('改变向量指纹')
 expect(mocks.call.mock.calls.every(call=>['services.get','services.save'].includes(call[1]))).toBe(true)
})
it('前缀按UTF-8字节限制，非零编码上限范围非法时不保存',async()=>{
 wrapper=mount(ServiceSettings);await flushPromises()
 await wrapper.get('[aria-label="文档编码前缀"]').setValue('文'.repeat(86))
 expect(wrapper.text()).toContain('258 / 256 UTF-8 字节')
 expect(wrapper.get('button[type="submit"]').element.disabled).toBe(true)
 await wrapper.get('form').trigger('submit');await flushPromises()
 expect(mocks.call.mock.calls.some(call=>call[1]==='services.save')).toBe(false)
 await wrapper.get('[aria-label="文档编码前缀"]').setValue('')
 await wrapper.get('[aria-label="单次编码字节上限"]').setValue(127)
 expect(wrapper.get('button[type="submit"]').element.disabled).toBe(true)
 await wrapper.get('form').trigger('submit');await flushPromises()
 expect(mocks.call.mock.calls.some(call=>call[1]==='services.save')).toBe(false)
 await wrapper.get('[aria-label="单次编码字节上限"]').setValue(128)
 expect(wrapper.get('button[type="submit"]').element.disabled).toBe(false)
 await wrapper.get('[aria-label="查询编码前缀"]').setValue('字'.repeat(43))
 expect(wrapper.get('button[type="submit"]').element.disabled).toBe(true)
 await wrapper.get('form').trigger('submit');await flushPromises()
 expect(mocks.call.mock.calls.some(call=>call[1]==='services.save')).toBe(false)
})
it('显式清除向量密钥不影响搜索密钥，域名允许列表按行提交',async()=>{
 wrapper=mount(ServiceSettings);await flushPromises()
 const clear=wrapper.findAll('label').find(label=>label.text()==='清除已保存的向量密钥').get('input')
 await clear.setValue(true)
 await wrapper.get('[aria-label="网页读取允许域名"]').setValue('example.com\nwiki.example.com')
 await wrapper.get('form').trigger('submit');await flushPromises()
 const saved=mocks.call.mock.calls.find(call=>call[1]==='services.save')[2]
 expect(saved.embedding.clear_key).toBe(true)
 expect(saved.embedding.api_key).toBe('')
 expect(saved.search.clear_key).toBe(false)
 expect(saved.web_read.allowed_hosts).toEqual(['example.com','wiki.example.com'])
})
